pixman: fix do_compile error
Issue: LIN1024-2382

When debug build is enabled(-Og is used), pixman-native do_compile
failed with error:
In function ‘combine_inner’,
    inlined from ‘combine_soft_light_ca_float’ at ../pixman-0.42.2/pixman/pixman-combine-float.c:655:1:
../pixman-0.42.2/pixman/pixman-combine-float.c:370:5: error: inlining failed in call to ‘always_inline’ ‘combine_soft_light_c’: function not considered for inlining
  370 |     combine_ ## name ## _c (float sa, float s, float da, float d)

Refer [1], always_inline is not suggested to use with indirect function
call, replace always_inline with __inline__ to fix the issue

[1] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107931

(LOCAL REV: NOT UPSTREAM) -- sent to oe-core on 20240705

Signed-off-by: Changqing Li <changqing.li@windriver.com>