kea: fix test build failure
Issue: LIN1024-5596

Fix unit test build failure:
process_spawn_unittest.cc: In member function ‘virtual void {anonymous}::ProcessSpawnTest_inheritEnv_Test::TestBody()’:
process_spawn_unittest.cc:370:18: error: ‘class isc::asiolink::IOService’ has no member named ‘runOne’; did you mean ‘run_one’?
  370 |     io_service_->runOne();
      |                  ^~~~~~
      |                  run_one

It was introduced by commit:
    commit ed1c74464240968d32200148cf9fcd04ff66f2ad
    Author: Yi Zhao <yi.zhao@windriver.com>
    Date:   Tue Dec 10 14:08:13 2024 +0800

    kea: make kea environment available to lfc

(LOCAL REV: NOT UPSTREAM) -- sent to oe-core on 20250307

Signed-off-by: Mikael Beckius <mikael.beckius@windriver.com>
Signed-off-by: Yi Zhao <yi.zhao@windriver.com>