json-c: avoid ptest failure caused by valgrind
Issue: LIN1024-3315

json-c's ptest will automatically detect valgrind and use it to run
tests. This will fail in case valgrind does not work, e.g., intel-x86-64
(corei7-64) + lib32 image. The error is about illegal instruction.
Error message is like below:

  Illegal instruction     (core dumped) valgrind --tool=memcheck ...
  ERROR: "test1Formatted spaced pretty" exited with non-zero exit status: 132

So we explicitly disable valgrind by exporting USE_VALGRIND=0.

(LOCAL REV: NOT UPSTREAM) -- sent to oe-core on 20240920

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>