lttng-modules: fix sched_stat_runtime changed in Linux 6.6.66
Issue: LIN1024-5825

The following commit has been backported into the 6.6.y branch.

See upstream commit:

    commit 5fe6ec8f6ab549b6422e41551abb51802bd48bc7
    Author: Peter Zijlstra <peterz@infradead.org>
    Date:   Mon Nov 6 13:41:43 2023 +0100

        sched: Remove vruntime from trace_sched_stat_runtime()

That caused building the lttng-modules report compile error:

       tracepoint-event-impl.h:133:6: error: conflicting types for
       'trace_sched_stat_runtime';

The fix is still pending on lttng review board, backport it to oe-core to
de-block the build issue.

(LOCAL REV: NOT UPSTREAM) -- Sent to oe-core on 20241222

Signed-off-by: Xiangyu Chen <xiangyu.chen@windriver.com>